<?php

namespace App\Filament\Resources\BranchResource\Pages;

use App\Filament\Resources\BranchResource;
use App\Models\User;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;

class EditBranch extends EditRecord
{
    protected static string $resource = BranchResource::class;

    protected function handleRecordUpdate(Model $record, array $data): Model
    {
        // update access User password if any
        if( isset($data['password']) && $data['password'] != '' ){
            $branchUser = User::find($record->user_id);
            $branchUser->password = $data['password'];
            $branchUser->save();
        }

        // get the address GPS coords
        $GPSCoords = getLatLong($data['address'] . ', '. $data['city']);
        $data['gps_lat'] = $GPSCoords['latitude'];
        $data['gps_lon'] = $GPSCoords['longitude'];

        // protect passwords
        unset($data['password']);

        return parent::handleRecordUpdate($record, $data); // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }
}
